import fs from 'fs';
import path from 'path';

import {
  PORTABLE_DATA_DIR_NAME,
  PORTABLE_LOGS_DIR_NAME,
  PORTABLE_MARKER_FILE_NAME,
  type PortableModeStatus,
} from '../shared/appSettings/portableMode';
import { DB_FILENAME } from './appConstants';

/**
 * Chromium cache directories that are safe to skip when migrating user data
 * between locations. Everything else (SQLite, Local Storage, cookies, skins,
 * openclaw state, skills, plugins, ...) is copied so the app is portable.
 */
export const PORTABLE_CACHE_DIR_NAMES: ReadonlySet<string> = new Set([
  'Cache',
  'Code Cache',
  'GPUCache',
  'DawnCache',
  'DawnGraphiteCache',
  'DawnWebGPUCache',
  'DawnWebGPUDiskCache',
  'GrShaderCache',
  'ShaderCache',
  'blob_storage',
]);

/** Paths that are always regenerated by Chromium / Electron. */
export const PORTABLE_SKIP_ENTRY_NAMES: ReadonlySet<string> = new Set([
  ...PORTABLE_CACHE_DIR_NAMES,
  'SingletonCookie',
  'SingletonLock',
  'SingletonSocket',
  'DevToolsActivePort',
]);

export type ResolvePortableBaseDirInput = {
  execPath: string;
  /** electron-builder's NSIS portable target exports the original exe dir. */
  portableExecutableDir?: string | null;
};

export const resolvePortableBaseDir = (input: ResolvePortableBaseDirInput): string | null => {
  const candidate =
    input.portableExecutableDir?.trim() ||
    (input.execPath?.trim() ? path.dirname(input.execPath) : '');
  if (!candidate) return null;
  const resolved = path.resolve(candidate);
  if (!resolved || resolved === path.parse(resolved).root) return null;
  return resolved;
};

export const getPortableMarkerPath = (baseDir: string): string =>
  path.join(baseDir, PORTABLE_MARKER_FILE_NAME);

export const getPortableDataDir = (baseDir: string): string =>
  path.join(baseDir, PORTABLE_DATA_DIR_NAME);

export const getPortableLogDir = (baseDir: string): string =>
  path.join(getPortableDataDir(baseDir), PORTABLE_LOGS_DIR_NAME);

export const isPortableMarkerPresent = (baseDir: string | null): boolean =>
  !!baseDir && fs.existsSync(getPortableMarkerPath(baseDir));

export type PortablePathsInput = {
  baseDir: string | null;
  defaultUserDataDir: string;
  portableExecutableDir?: string | null;
  execPath?: string;
  supported: boolean;
  unsupportedReason?: string;
};

export const buildPortableModePaths = (input: PortablePathsInput): PortableModeStatus => ({
  active: isPortableMarkerPresent(input.baseDir),
  baseDir: input.baseDir,
  dataDir: input.baseDir ? getPortableDataDir(input.baseDir) : null,
  logDir: input.baseDir ? getPortableLogDir(input.baseDir) : null,
  defaultUserDataDir: input.defaultUserDataDir,
  markerPath: input.baseDir ? getPortableMarkerPath(input.baseDir) : null,
  supported: input.supported,
  unsupportedReason: input.unsupportedReason,
});

export const portableDataDirHasDatabase = (dataDir: string): boolean =>
  fs.existsSync(path.join(dataDir, DB_FILENAME));

export type CopyPortableDataResult = {
  copied: boolean;
  skipped: boolean;
  error?: string;
};

/**
 * Copy user-data content from one directory to another, skipping Chromium
 * caches and SQLite files (the database is migrated separately through the
 * online backup API while the app is running).
 */
export const copyPortableDataSync = (
  sourceDir: string,
  targetDir: string,
): CopyPortableDataResult => {
  try {
    if (!fs.existsSync(sourceDir)) return { copied: false, skipped: true };
    if (portableDataDirHasDatabase(targetDir)) {
      return { copied: false, skipped: true };
    }
    fs.mkdirSync(targetDir, { recursive: true });
    const shouldSkip = (src: string): boolean => {
      const name = path.basename(src);
      if (PORTABLE_SKIP_ENTRY_NAMES.has(name)) return true;
      if (name === DB_FILENAME || name.startsWith(`${DB_FILENAME}-`)) return true;
      return false;
    };
    fs.cpSync(sourceDir, targetDir, {
      recursive: true,
      force: true,
      verbatimSymlinks: true,
      filter: src => !shouldSkip(src),
    });
    return { copied: true, skipped: false };
  } catch (error) {
    return {
      copied: false,
      skipped: false,
      error: error instanceof Error ? error.message : 'Failed to copy user data',
    };
  }
};
